version: "3.5"

services:
  redis:
    # https://hub.docker.com/_/redis/
    image: redis:5.0.6
    ports:
      - 6379:6379

  app:
    build: ./
    ports:
      - 8080:8080
    environment:
      REDIS_DSN: "redis:6379"


